### ISSUE TITLE
Add support for Issues

### ISSUE THREAD

**Issue by derekpovah** [craftamap/bb#9]
Believe it or not, there are some of us that use Bitbucket issues instead of Jira for our bug tracker. After looking at the library you are using to talk to Bitbucket, I see that it doesn't support issues either, so I raised ktrysmt/go-bitbucket/issues/133 over there.

**Comment by craftamap** [comment]
Hey @derekpovah !

Sounds like a cool feature, I will take a look into it :)

**Comment by craftamap** [comment]
I will do some general bugfixes, but the feature will be released soon :)

**Comment by craftamap** [comment]
@derekpovah v0.4.0 just got released :)

**Comment by derekpovah** [comment]
@craftamap Fastest feature request deployment ever. You are awesome.
